### ISSUE TITLE
Error while clicking load Game Mod button "C:\Temp\DualSenseX\DualSenseX_PortNumber.txt"

### ISSUE THREAD

**Issue by osmanerdem** [josealissonbr/DualSenseAT#14]
Hi, 

This the first time I ve installed dualsenseX and dualsenseAT

When I tried to open God of War, 

1) I firstly started DualsenseX
2) Secondly started dualseneAT
3) Started God Of War via steam,
4) Then I clicked to load game Mod from dualsense

But at that moment this Error appears with red cross.

"Unhandled exception has occurred in your application.
'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt' not found

and I can see details by clicking details button. I paste here the full error. it is Turkish but gives information.

What do you reccomend to me?

```
The FULL details

System.IO.FileNotFoundException: 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt' dosyası bulunamadı.
Dosya adı: 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt'
   konum: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   konum: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   konum: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   konum: System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   konum: System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   konum: ETS2_DualSenseAT_Mod.Form1.Form1_Load(Object sender, EventArgs e)
   konum: System.Windows.Forms.Form.OnLoad(EventArgs e)
   konum: System.Windows.Forms.Form.OnCreateControl()
   konum: System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   konum: System.Windows.Forms.Control.CreateControl()
   konum: System.Windows.Forms.Control.WmShowWindow(Message& m)
   konum: System.Windows.Forms.Control.WndProc(Message& m)
   konum: System.Windows.Forms.Form.WmShowWindow(Message& m)
   konum: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Yüklü Derlemeler
mscorlib
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

dsx_1593500
    Bütünleştirilmiş Kod Sürümü: 1.0.0.0
    Win32 Sürümü: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DualSenseAT/temp/1593500/download/dsx_1593500.exe

System.Windows.Forms
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Memory
    Bütünleştirilmiş Kod Sürümü: 1.2.23.0
    Win32 Sürümü: 1.2.23.0
    CodeBase: file:///C:/Program%20Files%20(x86)/DualSenseAT/temp/1593500/download/Memory.DLL

netstandard
    Bütünleştirilmiş Kod Sürümü: 2.0.0.0
    Win32 Sürümü: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll

System.Configuration
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

mscorlib.resources
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/mscorlib.resources.dll

System.Windows.Forms.resources
    Bütünleştirilmiş Kod Sürümü: 4.0.0.0
    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/System.Windows.Forms.resources.dll


JIT Hata Ayıklama
JIT hata ayıklamayı etkinleştirmek için, bu uygulamanın veya
bilgisayarın (machine.config) .config dosyasında
system.windows.forms bölümünde jitDebugging değeri ayarlanmış olmalıdır.
Ayrıca uygulama hata ayıklama etkin durumdayken derlenmiş
olmalıdır.

JIT hata ayıklama etkinken, işlenmemiş özel durumlar
bu iletişim kutusunda işlenmek yerine bilgisayarda kayıtlı
JIT hata ayıklayıcısına gönderilir.
```

**Comment by josealissonbr** [comment]
Create the file in ‘'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt’

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Osman Erdem ***@***.***>
Enviado:domingo, 12 de fevereiro de 2023 15:40
Para: ***@***.***>
***@***.***>
Assunto: [josealissonbr/DualSenseAT] Error acter clicking load Game Mod System.IO.FileNotFoundException: DualSenseX_PortNumber.txt' not found (Issue #14)


Hi,

This the first time I ve installed dualsenseX and dualsenseAT

When I tried to open God of War,

  1.  I firstly started DualsenseX
  2.  Secondly started dualseneAT
  3.  Started God Of War via steam,
  4.  Then I clicked to load game Mod from dualsense

But at that moment this Error appears with red cross.

"Unhandled exception has occurred in your application.
'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt' not found

and I can see details by clicking details button. I paste here the full error. it is Turkish but gives information.

What do you reccomend to me?

The FULL details







System.IO.FileNotFoundException: 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt' dosyası bulunamadı.



Dosya adı: 'C:\Temp\DualSenseX\DualSenseX_PortNumber.txt'



   konum: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)



   konum: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)



   konum: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)



   konum: System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)



   konum: System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)



   konum: ETS2_DualSenseAT_Mod.Form1.Form1_Load(Object sender, EventArgs e)



   konum: System.Windows.Forms.Form.OnLoad(EventArgs e)



   konum: System.Windows.Forms.Form.OnCreateControl()



   konum: System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)



   konum: System.Windows.Forms.Control.CreateControl()



   konum: System.Windows.Forms.Control.WmShowWindow(Message& m)



   konum: System.Windows.Forms.Control.WndProc(Message& m)



   konum: System.Windows.Forms.Form.WmShowWindow(Message& m)



   konum: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)











Yüklü Derlemeler



mscorlib



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4515.0 built by: NET48REL1LAST_C



    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll







dsx_1593500



    Bütünleştirilmiş Kod Sürümü: 1.0.0.0



    Win32 Sürümü: 1.0.0.0



    CodeBase: file:///C:/Program%20Files%20(x86)/DualSenseAT/temp/1593500/download/dsx_1593500.exe







System.Windows.Forms



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4550.0 built by: NET48REL1LAST_C



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll







System



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4605.0 built by: NET48REL1LAST_C



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll







System.Drawing



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4390.0 built by: NET48REL1LAST_C



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll







Memory



    Bütünleştirilmiş Kod Sürümü: 1.2.23.0



    Win32 Sürümü: 1.2.23.0



    CodeBase: file:///C:/Program%20Files%20(x86)/DualSenseAT/temp/1593500/download/Memory.DLL







netstandard



    Bütünleştirilmiş Kod Sürümü: 2.0.0.0



    Win32 Sürümü: 4.8.4084.0



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll







System.Configuration



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4190.0 built by: NET48REL1LAST_B



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll







System.Core



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4605.0 built by: NET48REL1LAST_C



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll







System.Xml



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll







mscorlib.resources



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/mscorlib.resources.dll







System.Windows.Forms.resources



    Bütünleştirilmiş Kod Sürümü: 4.0.0.0



    Win32 Sürümü: 4.8.4084.0 built by: NET48REL1



    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_tr_b77a5c561934e089/System.Windows.Forms.resources.dll











JIT Hata Ayıklama



JIT hata ayıklamayı etkinleştirmek için, bu uygulamanın veya



bilgisayarın (machine.config) .config dosyasında



system.windows.forms bölümünde jitDebugging değeri ayarlanmış olmalıdır.



Ayrıca uygulama hata ayıklama etkin durumdayken derlenmiş



olmalıdır.







JIT hata ayıklama etkinken, işlenmemiş özel durumlar



bu iletişim kutusunda işlenmek yerine bilgisayarda kayıtlı



JIT hata ayıklayıcısına gönderilir.

**Comment by osmanerdem** [comment]
Hello @josealissonbr 

Thanks for advice. But I have already tested it. It gives this error

**System.FormatException: Input string was not in a correct format.**

`See the end of this message for details on invoking `
`
just-in-time (JIT) debugging instead of this dialog box
 Exception Text
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at ETS2_DualSenseAT_Mod.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by josealissonbr** [comment]
> 
Probably DualsenseX updated, unfortunately I stopped updating this repository for a while, but if you understand C# it can correct you, you will also understand how DSAT works xD
