### ISSUE TITLE
DualsenseX_GameTriggers.txt not generated for ets2

### ISSUE THREAD

**Issue by TheDoctor40** [josealissonbr/DualSenseAT#5]
DSX and ETS2 are both installed through Steam. ets2-sdk-plugin installed from the link in the wiki. 
Started ETS2 first, loaded up a save. Then started DualSenseAT. However, when I start DSX and try to load the C:\DualsenseX_GameTriggers.txt file, I can't find it anywhere. It looks like it is not being generated.

**Comment by Kurochi51** [comment]
I have the same issue, I tried disabling / enabling steam input, reinstalled both the game and dualsenseAT, I searched all drives, but the file just isn't created.

**Comment by josealissonbr** [comment]
If I'm not mistaken, it is no longer necessary to use TXT files, as the communication between DSAT and DSX is done through a communication protocol
